sqlite3 forum.sqlite3 < migrations/01_add_user_table.sql
sqlite3 forum.sqlite3 < migrations/02_add_post_table.sql
sqlite3 forum.sqlite3 < migrations/03_add_category_table.sql
sqlite3 forum.sqlite3 < migrations/04_add_session_table.sql
sqlite3 forum.sqlite3 < migrations/05_add_comment_table.sql
sqlite3 forum.sqlite3 < migrations/06_add_post_vote_table.sql
sqlite3 forum.sqlite3 < migrations/07_insert_categories.sql
sqlite3 forum.sqlite3 < migrations/08_add_post_categories.sql
sqlite3 forum.sqlite3 < migrations/09_add_comment_vote_table.sql